### ISSUE TITLE
No longer works following release of compat_resource 12.5.26

### ISSUE THREAD

**Issue by ianbamforth** [chef-cookbooks/rsyslog#106]
NoMethodError:
       undefined method `action' for #<Class:0x00000003339840> action provider

Not sure whether this lies with this cookbook or compat_resource, but I've had to lock down the version of compat_resource to get my build pipeline back in order.  Appears there has been some work in this area relating to action in the compat_resource cookbook.

**Comment by tas50** [comment]
That's an issue with compat_resource.  I imagine it's resolved with the latest release, but if not please file the bug there.
