### ISSUE TITLE
Releases should follow semver

### ISSUE THREAD

**Issue by eheydrick** [chef-cookbooks/rsyslog#113]
I noticed the most recent release, 4.0.1, was a patch release but added some new functionality - namely the config validation, tls_permitted_peer, and support for suse. According to semver and the [contribution guidelines](https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD#release-cycle) new functionality should be released in a minor version. As a consumer of community cookbooks I use the version numbering in my decision for how much scrutiny and testing to give to a release therefore it would be good if all releases followed semver.

**Comment by iennae** [comment]
Apologies for the mistake in versioning @eheydrick. I viewed the config validation and repairing the SUSE support as bug fixes. I will be more liberal in bumping versions based on changes.
