### ISSUE TITLE
rsyslog.conf.erb contains hardcoded values and missing attributes

### ISSUE THREAD

**Issue by rmcleod8** [chef-cookbooks/rsyslog#123]
### Cookbook version
5.0.1

### Chef-client version
12.9.41

### Platform Details
rhel6.8

### Scenario:
Attempting to set the Umask, FileCreateMode, DirCreateMode, DirOwner, DirGroup, Template directives. However Umask, FileCreateMode, DirCreateMode are hardcoded values in the rsyslog.conf.erb and DirOwner, DirGroup, Template do not exist as available attributes.

### Steps to Reproduce:
(Not a bug just missing functionality) 
Open the rsyslog.conf.erb and note that lines 92, 93, 94 are hardcoded values  preventing the user from changing them. 
Also note that the attributes/default.rb is missing attributes for Umask, FileCreateMode, DirCreateMode, DirOwner, DirGroup, Template directives

**Comment by tas50** [comment]
Fixed in 5.1
