### ISSUE TITLE
Cookbook doesn't support package names other than "rsyslog"

### ISSUE THREAD

**Issue by simfish85** [chef-cookbooks/rsyslog#125]
The cookbook doesn't support different rsyslog package name other than "rsyslog", on Red Hat 5 and 6 you can choose different rsyslog versions (on main update repo) like "rsyslog" or "rsyslog7". So if you have different version https://github.com/chef-cookbooks/rsyslog/blob/master/recipes/client.rb will fail on install part. So I think cookbook should needs an attribute with package name.

**Comment by simfish85** [comment]
@aivaraslaimikis

**Comment by aivaraslaimikis** [comment]
Commit merged. Issue can be closed.
