### ISSUE TITLE
Issue supporting multiple remote servers

### ISSUE THREAD

**Issue by simfish85** [chef-cookbooks/rsyslog#126]
Cookbook supports multiple remote servers. But this is not implemented as should be. By documentation http://www.rsyslog.com/doc/v8-stable/tutorials/reliable_forwarding.html , when there is more than 1 remote server, client should create more queues with different names. So this part https://github.com/chef-cookbooks/rsyslog/blob/master/templates/default/49-remote.conf.erb is wrong, because here it is hardcoded that there is only 1 queue.

**Comment by simfish85** [comment]
@aivaraslaimikis

**Comment by iennae** [comment]
Thanks @aivaraslaimikis for your PR to fix this issue. As of cookbook version 6.0.1 this has been released.
