### ISSUE TITLE
Add Update option

### ISSUE THREAD

**Issue by vorgusa** [chef-cookbooks/rsyslog#137]
### Cookbook version
6.0.1

Feature request:
Add ability to install latest version of rsyslog or newer.  We are trying to use an external yum repo to get a newer RPM, but the cookbook does not allow us to set it to latest

**Comment by tas50** [comment]
Updating packages is something we try to keep out of cookbooks. It's a pretty easy thing to add in a wrapper if you want control of how updates occur. In general it makes people pretty nervous in community cookbooks so we avoid it.
