### ISSUE TITLE
Feature Request: Support for both TCP and UDP in rsyslog.conf

### ISSUE THREAD

**Issue by andrewfraley** [chef-cookbooks/rsyslog#60]
I'd like to support TCP and UDP concurrently in rsyslog.conf.  An option for "both" could be added for node['rsyslog']['protocol'], but this attribute is used elsewhere in the client side configs.  Perhaps a new attribute could be added such as node['rsyslog']['server_protocol'].

**Comment by gmccue** [comment]
@andrewfraley This features was added in v2.1.0. You can allow both protocols by setting ```node['rsyslog']['protocol'] = 'udptcp'``` as explained here: https://github.com/opscode-cookbooks/rsyslog#attributes.

**Comment by iennae** [comment]
Apologies in the followup here. @andrewfraley as @gmccue has mentioned, this feature was added in cookbook version 2.1.0. You would use the attribute you have indicated with the specific value of udptcp.
