### ISSUE TITLE
rsyslog deprecation

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/rsyslog#82]
Using rsyslog 7.6.3 (wheezy-backports) on Debian throws a deprecation warning:

`rsyslogd-2184:  action '*' treated as ':omusrmsg:*' - please change syntax, '*' will not be supported in the future [try http://www.rsyslog.com/e/2184 ]`

see: http://lists.adiscon.net/pipermail/rsyslog/2012-October/030845.html
and: https://github.com/opscode-cookbooks/rsyslog/blob/81252ccea0b7647c3692cdfc1cd7930e63430438/attributes/default.rb#L95

I'm an rsyslog noob, so I'm not sure if fixing this breaks older versions.

**Comment by tas50** [comment]
I've fixed this in the latest cookbook release, but I'm unsure if it will break compatibility with older rsyslog on centos 5.  I need to test before doing a release.
