### ISSUE TITLE
Enable ability to specify installation of newer versions of rsyslog via source

### ISSUE THREAD

**Issue by hartfordfive** [chef-cookbooks/rsyslog#96]
I've recently come across a situation where I needed to install rsyslog 8.13.0 and unfortunately had to do it from scratch because this cookbook didn't have that option.  Also, having the ability to specify `--configure` parameters would be useful especially when you want to enable non-standard plugins such as omhiredis.

**Comment by tas50** [comment]
We're trying to avoid source installs anywhere in our community cookbooks at this point.  The complexity level introduced is not worth the functionality added.  What you can do is manage either a PPA or a yum repo in a wrapper cookbook.  I did this in the past and it's a very simple solution to ensuring you get the latest packages while still getting the management this cookbook provides.
