### ISSUE TITLE
2.2.0 broke omrelp

### ISSUE THREAD

**Issue by docwhat** [chef-cookbooks/rsyslog#98]
I keep getting lines like this my `49-remote.conf` file when using `rsyslog::client`:

```
*.* :omrelp:{"server"=>"10.0.10.10", "port"=>514, "logs"=>"*.*", "protocol"=>"tcp", "remote_template"=>"RSYSLOG_ForwardFormat"}:20514;RSYSLOG_ForwardFormat
```

The bit in the `{...}` characters seems to be the ruby expression of `rsyslog_servers` in version 2.2.0.

Rolling back to 2.1.0 fixes this problem.

**Comment by docwhat** [comment]
BTW: What I expected was:

```
*.* :omrelp:10.0.10.10:20514;RSYSLOG_ForwardFormat
```

**Comment by tas50** [comment]
Fixing that now and working out a test to make sure we actually valid relp in the future

**Comment by tas50** [comment]
Should be fixed in master now.  Thanks for the example of what it should look like.

**Comment by docwhat** [comment]
W00T!
